### ISSUE TITLE
Widgets: Personal and User Performance dashboard shows empty charts

### ISSUE THREAD

**Issue by okamara** [qaprosoft/qps-infra#213] opened 2020-06-18 09:04 UTC
Env. : jenkins:5.1_beta3;qps-infra - develop; pipeline- develop

<img width="1439" alt="Screen Shot 2020-06-18 at 12 02 41 PM" src="https://user-images.githubusercontent.com/32964663/85001056-db715780-b15b-11ea-9610-923c4aa7c92d.png">

**Comment by vdelendik** [comment] 2020-06-18 09:40
not a bug. when you just open "personal" board zafira shows tests belonging to logged user now. There is no test assigned to "admin" so dashboard is empty!
To be able to see persoanl board of the anonymous you can open General and click on "anonymous" user/link.
it will open personal board but using explicit anonymous id in the address: http://54.193.74.120/app/dashboards/1?userId=1

and you will see correct results as by default all tests are assigned to anonymous

**Closed by vdelendik** 2020-06-18 09:40 UTC
Labels: bug
